#!/usr/bin/env bash
#ssh client configuration

Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    PasswordAuthentication no
    IdentityFile ~/.ssh/holberton
